// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'package:ecommerecstore/firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB360lUdEfZ2gDi98TDQH2879DgbmFVu_8',
    appId: '1:210548096618:web:0018324b6e95a3d6995413',
    messagingSenderId: '210548096618',
    projectId: 'flutter-firebase-auth-c6d6c',
    authDomain: 'flutter-firebase-auth-c6d6c.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-c6d6c.firebasestorage.app',
    measurementId: 'G-HPTD71VZ0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIBFrp92jbK3PT90NO_t8-Jg8hM_4G7D4',
    appId: '1:210548096618:android:0614e29b1c0fff81995413',
    messagingSenderId: '210548096618',
    projectId: 'flutter-firebase-auth-c6d6c',
    storageBucket: 'flutter-firebase-auth-c6d6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAwjC4OCmd4QttXtV1gxbN9SQc1hZHyBM',
    appId: '1:210548096618:ios:26d50ed4cc9e3957995413',
    messagingSenderId: '210548096618',
    projectId: 'flutter-firebase-auth-c6d6c',
    storageBucket: 'flutter-firebase-auth-c6d6c.firebasestorage.app',
    androidClientId:
        '210548096618-9vvpbi1vc001ddcopjkdvok6vk7q70qi.apps.googleusercontent.com',
    iosClientId:
        '210548096618-ntbcd5k3vu5o46uhnv57bg5b3goh772h.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerecstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB360lUdEfZ2gDi98TDQH2879DgbmFVu_8',
    appId: '1:210548096618:web:0837eee712a4e5a3995413',
    messagingSenderId: '210548096618',
    projectId: 'flutter-firebase-auth-c6d6c',
    authDomain: 'flutter-firebase-auth-c6d6c.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-c6d6c.firebasestorage.app',
    measurementId: 'G-SPZ2R26MMY',
  );
}
